[theme]
background         = "#000000"
primary            = "#777777"
secondary          = "#777777"
title              = "#FFFFFF"
playing            = "#FFFFFF"
playing_selected   = "#FFFFFF"
playing_bg         = "#000000"
highlight          = "#777777"
highlight_bg       = "#222222"
error              = "#FF0000"
error_bg           = "#000000"
statusbar          = "#FFFFFF"
statusbar_progress = "#FFFFFF"
statusbar_bg       = "#000000"
cmdline            = "#777777"
cmdline_bg         = "#000000"
